# FOX BOOTSTRAP — Windows PowerShell
# Jalanin ini pas pertama kali clone repo.
# AI akan auto-execute ini setelah baca README.

$FOX_HOME = if ($env:FOX_HOME) { $env:FOX_HOME } else { "$env:USERPROFILE\.fox" }
$VAULT_DIR = "$FOX_HOME\vault"
$MULTIBRAIN_DIR = "$FOX_HOME\multibrain"
$REPO_DIR = Split-Path -Parent $PSScriptRoot

Write-Host "🦊 FOX BOOTSTRAP — Initializing local environment..." -ForegroundColor Red
Write-Host "Target: $FOX_HOME" -ForegroundColor Cyan

# ─── Vault Structure ───
$VAULT_SUBDIRS = @(
    "targets",
    "combos",
    "hashes",
    "tokens",
    "keys",
    "sessions",
    "cracking",
    "logs"
)

foreach ($dir in $VAULT_SUBDIRS) {
    $path = "$VAULT_DIR\$dir"
    if (-not (Test-Path $path)) {
        New-Item -ItemType Directory -Path $path -Force | Out-Null
        Write-Host "  [+] Created vault/$dir" -ForegroundColor Green
    } else {
        Write-Host "  [•] vault/$dir already exists" -ForegroundColor Yellow
    }
}

# ─── Multibrain Structure ───
$MULTIBRAIN_SUBDIRS = @(
    "indexes",
    "context"
)

foreach ($dir in $MULTIBRAIN_SUBDIRS) {
    $path = "$MULTIBRAIN_DIR\$dir"
    if (-not (Test-Path $path)) {
        New-Item -ItemType Directory -Path $path -Force | Out-Null
        Write-Host "  [+] Created multibrain/$dir" -ForegroundColor Green
    } else {
        Write-Host "  [•] multibrain/$dir already exists" -ForegroundColor Yellow
    }
}

# ─── Session File ───
$SESSION_FILE = "$MULTIBRAIN_DIR\session.md"
if (-not (Test-Path $SESSION_FILE)) {
    @"
# MultiBrain Session — Fox
# Auto-generated by bootstrap

## Active Ops
(None)

## Last Updated
$(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
"@ | Set-Content -Path $SESSION_FILE
    Write-Host "  [+] Created multibrain/session.md" -ForegroundColor Green
}

# ─── Vault Master Index ───
$VAULT_INDEX = "$VAULT_DIR\master-index.md"
if (-not (Test-Path $VAULT_INDEX)) {
    @"
# FOX VAULT — Master Index
# Auto-generated by bootstrap

## Structure
$VAULT_DIR
"@ | Set-Content -Path $VAULT_INDEX
    Write-Host "  [+] Created vault/master-index.md" -ForegroundColor Green
}

# ─── Symlink repo skills (optional) ───
$SKILLS_LINK = "$FOX_HOME\skills"
if (-not (Test-Path $SKILLS_LINK)) {
    $REPO_SKILLS = "$REPO_DIR\skills"
    if (Test-Path $REPO_SKILLS) {
        New-Item -ItemType Junction -Path $SKILLS_LINK -Target $REPO_SKILLS -Force | Out-Null
        Write-Host "  [+] Linked skills/ -> repo" -ForegroundColor Green
    }
}

Write-Host ""
Write-Host "✅ FOX BOOTSTRAP COMPLETE" -ForegroundColor Green
Write-Host "   Vault: $VAULT_DIR" -ForegroundColor Cyan
Write-Host "   Multibrain: $MULTIBRAIN_DIR" -ForegroundColor Cyan
Write-Host ""
Write-Host "🦊 Fox is ready. SYNS4033's word is law." -ForegroundColor Red
