#!/bin/bash
# FOX BOOTSTRAP — Linux/macOS
# Jalanin ini pas pertama kali clone repo.
# AI akan auto-execute ini setelah baca README.

FOX_HOME="${FOX_HOME:-$HOME/.fox}"
VAULT_DIR="$FOX_HOME/vault"
MULTIBRAIN_DIR="$FOX_HOME/multibrain"
REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"

echo -e "\033[0;31m🦊 FOX BOOTSTRAP — Initializing local environment...\033[0m"
echo -e "\033[0;36mTarget: $FOX_HOME\033[0m"

# ─── Vault Structure ───
for dir in targets combos hashes tokens keys sessions cracking logs; do
    mkdir -p "$VAULT_DIR/$dir"
    echo -e "\033[0;32m  [+] Created vault/$dir\033[0m"
done

# ─── Multibrain Structure ───
for dir in indexes context; do
    mkdir -p "$MULTIBRAIN_DIR/$dir"
    echo -e "\033[0;32m  [+] Created multibrain/$dir\033[0m"
done

# ─── Session File ───
if [ ! -f "$MULTIBRAIN_DIR/session.md" ]; then
    cat > "$MULTIBRAIN_DIR/session.md" << 'EOF'
# MultiBrain Session — Fox
# Auto-generated by bootstrap

## Active Ops
(None)

## Last Updated
EOF
    echo "$(date '+%Y-%m-%d %H:%M:%S')" >> "$MULTIBRAIN_DIR/session.md"
    echo -e "\033[0;32m  [+] Created multibrain/session.md\033[0m"
fi

# ─── Vault Master Index ───
if [ ! -f "$VAULT_DIR/master-index.md" ]; then
    cat > "$VAULT_DIR/master-index.md" << EOF
# FOX VAULT — Master Index
# Auto-generated by bootstrap

## Structure
$VAULT_DIR
EOF
    echo -e "\033[0;32m  [+] Created vault/master-index.md\033[0m"
fi

# ─── Symlink repo skills ───
if [ ! -L "$FOX_HOME/skills" ] && [ -d "$REPO_DIR/skills" ]; then
    ln -sf "$REPO_DIR/skills" "$FOX_HOME/skills" 2>/dev/null
    echo -e "\033[0;32m  [+] Linked skills/ -> repo\033[0m"
fi

echo ""
echo -e "\033[0;32m✅ FOX BOOTSTRAP COMPLETE\033[0m"
echo -e "\033[0;36m   Vault: $VAULT_DIR\033[0m"
echo -e "\033[0;36m   Multibrain: $MULTIBRAIN_DIR\033[0m"
echo ""
echo -e "\033[0;31m🦊 Fox is ready. SYNS4033's word is law.\033[0m"
